services:
  mongo:
    image: mongo:4.4.21
    container_name: restful-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    env_file:
      - ./.env
    ports:
      - '27017:27017'
    volumes:
      - restful-mongo:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data.json:/data/data.json
volumes:
  restful-mongo:
